version: '3.8'

services:
  app:
    image: tonioluc/php-laravel:latest
    container_name: cadeau_noel_app
    restart: unless-stopped  # Ajoutez cette ligne
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker-entrypoint.sh:/docker-entrypoint.sh  # Montage du script
      - cadeau_noel_composer_cache:/var/www/.composer/cache
    networks:
      - cadeau_noel
    depends_on:
      mysql :
        condition: service_healthy  # Attend que MySQL soit healthy
    environment:
      - COMPOSER_HOME=/var/www/.composer  # Important pour les permissions
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"]  # Utilise le script au lieu de php-fpm directement
    command: []  # Commande simple

  nginx:
    image: nginx:alpine
    container_name: cadeau_noel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cadeau_noel
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: cadeau_noel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cadeau_noel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: cadeau_secret
      MYSQL_USER: cadeau_noel
    ports:
      - "3306:3306"
    volumes:
      - cadeau_noel_mysql_data:/var/lib/mysql
    networks:
      - cadeau_noel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  cadeau_noel:
    driver: bridge

volumes:
  cadeau_noel_mysql_data:
  cadeau_noel_composer_cache: